{{- if .Values.oms.enabled }}
apiVersion: v1
kind: ConfigMap
metadata:
  name: '{{ .Release.Name }}-oms-configmap'
  namespace: {{ .Release.Namespace }}
data: # OMS Configuration Map -- ONLY ENVIRONMENT VARIABLES SUPPORTED: Order of Components -> UAG -> OMS -> UBR -> UEM -> UDM
{{- include "uac.emitIfSet" (dict "name" "UAGAGENTCLUSTERS" "value" .Values.omsConfig.uagagentclusters) }}
{{- include "uac.emitIfSet" (dict "name" "UAGBUSINESSSERVICES" "value" .Values.omsConfig.businessservices) }}
{{- include "uac.emitIfSet" (dict "name" "UAGEXTACCEPTLIST" "value" .Values.omsConfig.extensionacceptlist) }}
{{- include "uac.emitIfSet" (dict "name" "UAGEXTCANCELTIMEOUT" "value" .Values.omsConfig.extensioncanceltimeout) }}
{{- include "uac.emitIfSet" (dict "name" "UAGEXTDEPLOYONREG" "value" .Values.omsConfig.extensiondeployonregistration) }}
{{- include "uac.emitIfSet" (dict "name" "UAGEXTPYTHONLIST" "value" .Values.omsConfig.extensionpythonlist) }}
{{- include "uac.emitIfSet" (dict "name" "UAGNETNAME" "value" .Values.omsConfig.netname) }}
{{- include "uac.emitIfSet" (dict "name" "UAGOMSSERVERS" "value" .Values.omsConfig.omsServers) }}
{{- include "uac.emitIfSet" (dict "name" "UAGPRCCANCELTIMEOUT" "value" .Values.omsConfig.processcanceltimeout) }}
  UAGTRANSIENT: "yes"
{{- include "uac.emitIfSet" (dict "name" "UAGAUTOSTART" "value" .Values.omsConfig.uagAutostart) }}
{{- include "uac.emitIfSet" (dict "name" "UAGLOGLVL" "value" .Values.omsConfig.uagLoglvl) }}
{{- include "uac.emitIfSet" (dict "name" "UAGLEVEL" "value" .Values.omsConfig.uagLevel) }}
{{- include "uac.emitIfSet" (dict "name" "UAGTLSSNIHOSTNAME" "value" .Values.omsConfig.uagtlssnihostname) }} 
{{- include "uac.emitIfSet" (dict "name" "OMSCODEPAGE" "value" .Values.omsConfig.codepage) }}
{{- include "uac.emitIfSet" (dict "name" "OMSDNSCACHETIMEOUT" "value" .Values.omsConfig.omsDNSCacheTimeout) }}
{{- include "uac.emitIfSet" (dict "name" "OMSINDEXCACHESIZE" "value" .Values.omsConfig.omsIndexCacheSize) }}
{{- include "uac.emitIfSet" (dict "name" "OMSMAXCONNECTIONS" "value" .Values.omsConfig.omsMaxConnections) }}
{{- include "uac.emitIfSet" (dict "name" "OMSMAXDATAFILESIZE" "value" .Values.omsConfig.maxfilesize) }}
{{- include "uac.emitIfSet" (dict "name" "OMSMAXMSGSIZE" "value" .Values.omsConfig.maxmessagesize) }}
{{- include "uac.emitIfSet" (dict "name" "OMSMAXSSLPROTOCOL" "value" .Values.omsConfig.omsMaxSSLProtocol) }}
{{- include "uac.emitIfSet" (dict "name" "OMSLANG" "value" .Values.omsConfig.omsLanguage) }}
{{- include "uac.emitIfSet" (dict "name" "OMSMINSSLPROTOCOL" "value" .Values.omsConfig.omsMinSSLProtocol) }}
{{- include "uac.emitIfSet" (dict "name" "OMSMSGCHUNKSIZE" "value" .Values.omsConfig.chunksize) }}
{{- include "uac.emitIfSet" (dict "name" "OMSMSGCLEANUPINTERVAL" "value" .Values.omsConfig.omsMSGCleanupInterval) }}
{{- include "uac.emitIfSet" (dict "name" "OMSMSGDATAFLUSHINT" "value" .Values.omsConfig.omsMSGDataFlushInt) }}
{{- include "uac.emitIfSet" (dict "name" "OMSMSGSUPPRESSIONLIST" "value" .Values.omsConfig.omsMSGSuppressionList) }}

{{- include "uac.emitIfSet" (dict "name" "OTEL_ENABLE_TRACING" "value" .Values.omsConfig.otelenabletracing) }}
{{- include "uac.emitIfSet" (dict "name" "OTEL_EXPORT_METRICS" "value" .Values.omsConfig.otelexportmetrics) }}
{{- include "uac.emitIfSet" (dict "name" "OTEL_METRICS_ENDPOINT" "value" .Values.omsConfig.otelmetricsendpoint) }}
{{- include "uac.emitIfSet" (dict "name" "OTEL_METRICS_EXPORT_INTERVAL" "value" .Values.omsConfig.otelmetricsexportinterval) }}
{{- include "uac.emitIfSet" (dict "name" "OTEL_SERVICE_NAME" "value" .Values.omsConfig.otelservicename) }}
{{- include "uac.emitIfSet" (dict "name" "OTEL_SSL_CA_CERT_PATH" "value" .Values.omsConfig.otelsslcacertpath) }}
{{- include "uac.emitIfSet" (dict "name" "OTEL_SSL_CLIENT_CERT_PATH" "value" .Values.omsConfig.otelsslclientcertpath) }}
{{- include "uac.emitIfSet" (dict "name" "OTEL_SSL_CLIENT_KEY_PATH" "value" .Values.omsConfig.otelsslclientkeypath) }}
{{- include "uac.emitIfSet" (dict "name" "OTEL_SSL_INSECURE_SKIP_VERIFY" "value" .Values.omsConfig.otelsslinsecureskipverify) }}
{{- include "uac.emitIfSet" (dict "name" "OTEL_TRACE_ENDPOINT" "value" .Values.omsConfig.oteltraceendpoint) }}
 
{{- include "uac.emitIfSet" (dict "name" "OMSREQUIRESSL" "value" .Values.omsConfig.omsRequiresSSL) }}
{{- include "uac.emitIfSet" (dict "name" "OMSSERVICEBACKLOG" "value" .Values.omsConfig.omsServiceBacklog) }}
{{- include "uac.emitIfSet" (dict "name" "OMSSVCIPADDR" "value" .Values.omsConfig.omsSVCIAddr) }}
{{- include "uac.emitIfSet" (dict "name" "OMSSVCPORT" "value" .Values.omsConfig.omsSVCIPort) }}
{{- include "uac.emitIfSet" (dict "name" "OMSSERVICETIMEOUT" "value" .Values.omsConfig.omsServiceTimeout) }}
{{- include "uac.emitIfSet" (dict "name" "OMSSSLCIPHERLIST" "value" .Values.omsConfig.sslcipherlist) }}
{{- include "uac.emitIfSet" (dict "name" "OMSSSLCIPHERSUITES" "value" .Values.omsConfig.sslciphersuites) }}
{{- include "uac.emitIfSet" (dict "name" "OMSTRACEFILELINES" "value" .Values.omsConfig.omstracefilelines) }}
{{- include "uac.emitIfSet" (dict "name" "OMSTRACETABLE" "value" .Values.omsConfig.omstracetable) }}
{{- include "uac.emitIfSet" (dict "name" "OMSAUTOSTART" "value" .Values.omsConfig.omsAutostart) }}

{{- include "uac.emitIfSet" (dict "name" "UBRACTIVITYMONITORING" "value" .Values.omsConfig.ubractivitymonitoring) }}
{{- include "uac.emitIfSet" (dict "name" "UBRCACERTS" "value" .Values.omsConfig.ubrcacerts) }}
{{- include "uac.emitIfSet" (dict "name" "UBRCERT" "value" .Values.omsConfig.ubrcert) }}
{{- include "uac.emitIfSet" (dict "name" "UBRCRL" "value" .Values.omsConfig.ubrcrl) }}
{{- include "uac.emitIfSet" (dict "name" "UBRCODEPAGE" "value" .Values.omsConfig.codepage) }}
{{- include "uac.emitIfSet" (dict "name" "UBRCOMPINFORETENTION" "value" .Values.omsConfig.ubrcompinforetention) }}
{{- include "uac.emitIfSet" (dict "name" "UBRCOMPONENTBACKLOG" "value" .Values.omsConfig.ubrcomponentbacklog) }}
{{- include "uac.emitIfSet" (dict "name" "UBRCMPPORT" "value" .Values.omsConfig.ubrcmpport) }}
{{- include "uac.emitIfSet" (dict "name" "UBRCTLSSLCIPHERLIST" "value" .Values.omsConfig.sslcipherlist) }}
{{- include "uac.emitIfSet" (dict "name" "UBRCTLSSLCIPHERSUITES" "value" .Values.omsConfig.sslciphersuites) }}
{{- include "uac.emitIfSet" (dict "name" "UBRDBFILEGENERATIONS" "value" .Values.omsConfig.ubrdbfilegenerations) }}
{{- include "uac.emitIfSet" (dict "name" "UBRDNSCACHETIMEOUT" "value" .Values.omsConfig.ubrdnscachetimeout) }}
{{- include "uac.emitIfSet" (dict "name" "UBRECDSACERT" "value" .Values.omsConfig.ubrecdsacert) }}
{{- include "uac.emitIfSet" (dict "name" "UBRECDSAPRIVATEKEYPWD" "value" .Values.omsConfig.ubrecdsaprivatekeypwd) }}
{{- include "uac.emitIfSet" (dict "name" "UBRECDSAPRIVATEKEY" "value" .Values.omsConfig.ubrecdsaprivatekey) }}
{{- include "uac.emitIfSet" (dict "name" "UBREVENTGENERATION" "value" .Values.omsConfig.ubreventgeneration) }}
{{- include "uac.emitIfSet" (dict "name" "UBRMAXSSLPROTOCOL" "value" .Values.omsConfig.omsMaxSSLProtocol) }}
{{- include "uac.emitIfSet" (dict "name" "UBRDEST" "value" .Values.omsConfig.ubrdest) }}
{{- include "uac.emitIfSet" (dict "name" "UBRLANG" "value" .Values.omsConfig.omsLanguage) }}
{{- include "uac.emitIfSet" (dict "name" "UBRLEVEL" "value" .Values.omsConfig.ubrlevel) }}
{{- include "uac.emitIfSet" (dict "name" "UBRMINSSLPROTOCOL" "value" .Values.omsConfig.omsMinSSLProtocol) }}
{{- include "uac.emitIfSet" (dict "name" "UBRMONITOREVENTEXP" "value" .Values.omsConfig.ubrmonitoreventexp) }}
{{- include "uac.emitIfSet" (dict "name" "UBRMOUNTPOINT" "value" .Values.omsConfig.ubrmountpoint) }}
{{- include "uac.emitIfSet" (dict "name" "UBRMOUNTPOINTMODE" "value" .Values.omsConfig.ubrmountpointmode) }}
{{- include "uac.emitIfSet" (dict "name" "UBRMSGSUPPRESSIONLIST" "value" .Values.omsConfig.ubrmsgsuppressionlist) }}
{{- include "uac.emitIfSet" (dict "name" "UBRPERSISTENTEVENTEXP" "value" .Values.omsConfig.ubrpersistenteventexp) }}
{{- include "uac.emitIfSet" (dict "name" "UBRPRIVATEKEY" "value" .Values.omsConfig.ubrprivatekey) }}
{{- include "uac.emitIfSet" (dict "name" "UBRPRIVATEKEYPWD" "value" .Values.omsConfig.ubrprivatekeypwd) }}
{{- include "uac.emitIfSet" (dict "name" "UBRREQUIRESSL" "value" .Values.omsConfig.omsRequiresSSL) }}
{{- include "uac.emitIfSet" (dict "name" "UBRRETRYMAXCOMP" "value" .Values.omsConfig.ubrretrymaxcomp) }}
{{- include "uac.emitIfSet" (dict "name" "UBRSAFKEYRING" "value" .Values.omsConfig.ubrsafkeyring) }}
{{- include "uac.emitIfSet" (dict "name" "UBRSAFKEYRINGLABEL" "value" .Values.omsConfig.ubrsafkeyringlabel) }}
{{- include "uac.emitIfSet" (dict "name" "UBRSERVICEBACKLOG" "value" .Values.omsConfig.ubrservicebacklog) }}
{{- include "uac.emitIfSet" (dict "name" "UBRSVCIPADDR" "value" .Values.omsConfig.ubrsvcipaddr) }}
{{- include "uac.emitIfSet" (dict "name" "UBRSVCPORT" "value" .Values.omsConfig.ubrsvcport) }}
{{- include "uac.emitIfSet" (dict "name" "UBRSHRMOUNTPOINT" "value" .Values.omsConfig.ubrshrmountpoint) }}
{{- include "uac.emitIfSet" (dict "name" "UBRSHRMOUNTPOINTMODE" "value" .Values.omsConfig.ubrshrmountpointmode) }}
{{- include "uac.emitIfSet" (dict "name" "UBRSMFEXITLOADLIBRARY" "value" .Values.omsConfig.ubrsmfexitloadlibrary) }}
{{- include "uac.emitIfSet" (dict "name" "UBRSSLIMPLEMENTATION" "value" .Values.omsConfig.ubrsslimplementation) }}
{{- include "uac.emitIfSet" (dict "name" "UBRSYSTEMID" "value" .Values.omsConfig.ubrsystemid) }}
{{- include "uac.emitIfSet" (dict "name" "UBRTCPRECVBUFFER" "value" .Values.omsConfig.ubrtcprecvbuffer) }}
{{- include "uac.emitIfSet" (dict "name" "UBRTCPSENDBUFFER" "value" .Values.omsConfig.ubrtcpsendbuffer) }}
{{- include "uac.emitIfSet" (dict "name" "UBRTRACEFILELINES" "value" .Values.omsConfig.ubrtracefilelines) }}
{{- include "uac.emitIfSet" (dict "name" "UCMDTRACETABLE" "value" .Values.omsConfig.ucmdtracetable) }}
{{- include "uac.emitIfSet" (dict "name" "UBRUCMDSTCSUPPORT" "value" .Values.omsConfig.ubrucmdstcsupport) }}
{{- include "uac.emitIfSet" (dict "name" "UBRUCMDPATH" "value" .Values.omsConfig.ubrucmdpath) }}

{{- include "uac.emitIfSet" (dict "name" "UEMAUTOSTART" "value" .Values.omsConfig.uemAutostart) }}

{{- include "uac.emitIfSet" (dict "name" "UDMACKWINDOW" "value" .Values.omsConfig.udmackwindow) }}
{{- include "uac.emitIfSet" (dict "name" "UDMALLOWREPLONRENAME" "value" .Values.omsConfig.udmallowreplonrename) }}
{{- include "uac.emitIfSet" (dict "name" "UDMBIFDIRECTORY" "value" .Values.omsConfig.udmbifdirectory) }}
{{- include "uac.emitIfSet" (dict "name" "UDMCACERTS" "value" .Values.omsConfig.udmcacerts) }}
{{- include "uac.emitIfSet" (dict "name" "UDMCERT" "value" .Values.omsConfig.udmcert) }}
{{- include "uac.emitIfSet" (dict "name" "UDMDAYSTILEXPIRE" "value" .Values.omsConfig.udmdaystilexpire) }}
{{- include "uac.emitIfSet" (dict "name" "UDMCRL" "value" .Values.omsConfig.udmcrl) }}
{{- include "uac.emitIfSet" (dict "name" "UDMCODEPAGE" "value" .Values.omsConfig.codepage) }}
{{- include "uac.emitIfSet" (dict "name" "UDMCTLSSLCIPHERLIST" "value" .Values.omsConfig.sslcipherlist) }}
{{- include "uac.emitIfSet" (dict "name" "UDMCTLSSLCIPHERSUITES" "value" .Values.omsConfig.sslciphersuites) }}
{{- include "uac.emitIfSet" (dict "name" "UDMENCRYPT" "value" .Values.omsConfig.udmencrypt) }}
{{- include "uac.emitIfSet" (dict "name" "UDMFRAMEINTERVAL" "value" .Values.omsConfig.udmframeinterval) }}
{{- include "uac.emitIfSet" (dict "name" "UDMIDLETIMEOUT" "value" .Values.omsConfig.udmidletimeout) }}
{{- include "uac.emitIfSet" (dict "name" "UDMKEEPALIIVEINTERVAL" "value" .Values.omsConfig.udmkeepaliveinterval) }}
{{- include "uac.emitIfSet" (dict "name" "UDMMAXSSLPROTOCOL" "value" .Values.omsConfig.omsMaxSSLProtocol) }}
{{- include "uac.emitIfSet" (dict "name" "UDMMERGELOG" "value" .Values.omsConfig.udmmergelog) }}
{{- include "uac.emitIfSet" (dict "name" "UDMLANG" "value" .Values.omsConfig.omsLanguage) }}
{{- include "uac.emitIfSet" (dict "name" "UDMLEVEL" "value" .Values.omsConfig.udmlevel) }}
{{- include "uac.emitIfSet" (dict "name" "UDMMINSSLPROTOCOL" "value" .Values.omsConfig.omsMinSSLProtocol) }}
{{- include "uac.emitIfSet" (dict "name" "UDMMODETYPE" "value" .Values.omsConfig.udmmodetype) }}
{{- include "uac.emitIfSet" (dict "name" "UDMMSGSUPPRESSIONLIST" "value" .Values.omsConfig.udmmsgsuppressionlist) }}
{{- include "uac.emitIfSet" (dict "name" "UDMDELAY" "value" .Values.omsConfig.udmdelay) }}
{{- include "uac.emitIfSet" (dict "name" "UDMNETWORKFAULTTOLERANT" "value" .Values.omsConfig.udmnetworkfaulttolerant) }}
{{- include "uac.emitIfSet" (dict "name" "UDMOPENRETRY" "value" .Values.omsConfig.udmopenretry) }}
{{- include "uac.emitIfSet" (dict "name" "UDMOPENRETRYCOUNT" "value" .Values.omsConfig.udmopenretrycount) }}
{{- include "uac.emitIfSet" (dict "name" "UDMOPENRETRYINTERVAL" "value" .Values.omsConfig.udmopenretryinterval) }}
{{- include "uac.emitIfSet" (dict "name" "UDMOUTBOUNDIP" "value" .Values.omsConfig.udmoutboundip) }}
{{- include "uac.emitIfSet" (dict "name" "UDMPLFDIRECTORY" "value" .Values.omsConfig.udmplfdirectory) }}
{{- include "uac.emitIfSet" (dict "name" "UDMPRIVATEKEY" "value" .Values.omsConfig.udmprivatekey) }}
{{- include "uac.emitIfSet" (dict "name" "UDMPRIVATEKEYPWD" "value" .Values.omsConfig.udmprivatekeypwd) }}
{{- include "uac.emitIfSet" (dict "name" "UDMPROXYCERTIFICATES" "value" .Values.omsConfig.udmproxycertificates) }}
{{- include "uac.emitIfSet" (dict "name" "UDMRETRYCOUNT" "value" .Values.omsConfig.udmretrycount) }}
{{- include "uac.emitIfSet" (dict "name" "UDMRETRYINTERVAL" "value" .Values.omsConfig.udmretryinterval) }}
{{- include "uac.emitIfSet" (dict "name" "UDMRECVBUFSSIZE" "value" .Values.omsConfig.udmrecvbufssize) }}
{{- include "uac.emitIfSet" (dict "name" "UDMPORT" "value" .Values.omsConfig.udmport) }}
{{- include "uac.emitIfSet" (dict "name" "UDMSAFKEYRING" "value" .Values.omsConfig.udmsafkeyring) }}
{{- include "uac.emitIfSet" (dict "name" "UDMSAFKEYRINGLABEL" "value" .Values.omsConfig.udmsafkeyringlabel) }}
{{- include "uac.emitIfSet" (dict "name" "UDMSCRIPT" "value" .Values.omsConfig.udmscript) }}
{{- include "uac.emitIfSet" (dict "name" "UDMOPTIONS" "value" .Values.omsConfig.udmoptions) }}
{{- include "uac.emitIfSet" (dict "name" "UDMSENDBUFSSIZE" "value" .Values.omsConfig.udmsendbufssize) }}
{{- include "uac.emitIfSet" (dict "name" "UDMSERVERSTOPCONDITIONS" "value" .Values.omsConfig.udmserverstopconditions) }}
{{- include "uac.emitIfSet" (dict "name" "UDMSIZEATTRIB" "value" .Values.omsConfig.udmsizeattrib) }}
{{- include "uac.emitIfSet" (dict "name" "UDMSSLIMPLEMENTATION" "value" .Values.omsConfig.udmsslimplementation) }}
{{- include "uac.emitIfSet" (dict "name" "UDMSYSTEMID" "value" .Values.omsConfig.udmsystemid) }}
{{- include "uac.emitIfSet" (dict "name" "UDMTCPNODELAY" "value" .Values.omsConfig.udmtcpnodelay) }}
{{- include "uac.emitIfSet" (dict "name" "UDMTCPRECVBUFFER" "value" .Values.omsConfig.udmtcprecvbuffer) }}
{{- include "uac.emitIfSet" (dict "name" "UDMTCPSENDBUFFER" "value" .Values.omsConfig.udmtcpsendbuffer) }}
{{- include "uac.emitIfSet" (dict "name" "UDMTRACEFILELINES" "value" .Values.omsConfig.udmtracefilelines) }}
{{- include "uac.emitIfSet" (dict "name" "UDMTRACETABLE" "value" .Values.omsConfig.udmtracetable) }}
{{- include "uac.emitIfSet" (dict "name" "UDMUCMDPATH" "value" .Values.omsConfig.udmucmdpath) }}
{{- include "uac.emitIfSet" (dict "name" "UDMUMASK" "value" .Values.omsConfig.udmumask) }}
{{- include "uac.emitIfSet" (dict "name" "UDMUSAPDPATH" "value" .Values.omsConfig.udmusapdpath) }}
{{- include "uac.emitIfSet" (dict "name" "UDMVERIFYHOSTNAME" "value" .Values.omsConfig.udmverifyhostname) }}
{{- end }}
