{{- if and (not .Values.credentials.existingSecret) (not .Values.keyVault.enabled) }}
apiVersion: v1
kind: Secret
metadata:
  name: {{ .Release.Name }}-passwords
  namespace: {{ include "uc.namespace" . }}
  labels:
    {{- include "universal-controller.labels" . | nindent 4 }}
    {{- with .Values.commonLabels }}
    {{- toYaml . | nindent 4 }}
    {{- end }}
    app.kubernetes.io/component: secrets
  annotations:
    immutable: "true"
type: Opaque
data:
  {{ .Values.credentials.passwordKey }}: {{ .Values.credentials.dbPassword | b64enc | quote }}
  {{ .Values.credentials.keystorePasswordKey }}: {{ .Values.credentials.keystorePassword | b64enc | quote }}
  {{ .Values.credentials.truststorePasswordKey }}: {{ .Values.credentials.truststorePassword | b64enc | quote }}
  {{ .Values.credentials.truststoreEncryptedKey }}: {{ .Values.credentials.truststorePasswordEncrypted | b64enc | quote }}
{{- end }}
