{{- $isAKS := include "ua.isAKS" . | eq "true" -}}
{{- if and $isAKS .Values.workloadIdentity.enabled }}
apiVersion: v1
kind: ServiceAccount
metadata:
  name: {{ .Values.workloadIdentity.serviceAccountName }}
  namespace: {{ .Release.Namespace }}
  labels:
    {{- include "universal-agent.labels" . | nindent 4 }}
  annotations:
    azure.workload.identity/client-id: {{ .Values.workloadIdentity.clientId | quote }}
{{- end }}
