{{- if and .Values.uaDeployment.persistence.enabled (eq .Values.uaDeployment.persistence.claimName "") }}
{{- if and .Values.uaDeployment.persistence.storageClassName .Values.uaDeployment.persistence.persistentVolumeName }}
{{- fail "You cannot set both storageClassName and persistentVolumeName in persistence settings" }}
{{- end }}
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: {{ .Release.Name }}-pvc
  namespace: {{ .Release.Namespace }}
spec:
  accessModes:
    {{- toYaml .Values.uaDeployment.persistence.accessMode | nindent 4 }}
  resources:
    requests:
      storage: {{ .Values.uaDeployment.persistence.size }}
  {{- if .Values.uaDeployment.persistence.storageClassName }}
  storageClassName: {{ .Values.uaDeployment.persistence.storageClassName }}
  {{- end }}
  {{- if .Values.uaDeployment.persistence.persistentVolumeName }}
  volumeName: {{ .Values.uaDeployment.persistence.persistentVolumeName }}
  {{- end }}
  {{- if .Values.uaDeployment.persistence.volumeMode }}
  volumeMode: {{ .Values.uaDeployment.persistence.volumeMode }}
  {{- end }}
{{- end }}
