{{- if and (.Values.istiosidecar.enabled) (not (.Capabilities.APIVersions.Has "route.openshift.io/v1")) }}
apiVersion: networking.istio.io/v1
kind: Gateway
metadata:
  name: '{{ .Release.Name }}-uac-gateway'
  namespace: {{ .Release.Namespace | quote }}
spec:
  selector:
    istio: ingressgateway

  servers:
  # 80: (optional) only for web host if you want http->https redirect
  - port:
      number: 80
      name: http
      protocol: HTTP
    hosts:
    - {{ .Values.istio.host | quote }}

  # 443: WEB — Istio terminates TLS (no cipher list set; defaults apply)
  - port:
      number: 443
      name: https-web
      protocol: HTTPS
    tls:
      mode: SIMPLE
      credentialName: {{ .Values.istio.hostCredentials }}    # cert for akspresales.stonebranchdev.cloud
      minProtocolVersion: {{ .Values.istio.TLSProtocol | quote }}
      maxProtocolVersion: {{ .Values.istio.TLSProtocol | quote }}     
    hosts:
    - {{ .Values.istio.host | quote }}

  # 444: OMS — raw TLS passthrough to the pod
  - port:
      number: {{ .Values.istio.omsConnectionPort }}
      name: tls-oms
      protocol: TLS
    tls:
      mode: PASSTHROUGH
    hosts:
    - {{ .Values.istio.host | quote }}
  # 445: UDM Node
  - port:
      number: {{ .Values.istio.udmConnectionPort }}
      name: udm-tls
      protocol: TLS
    tls:
      mode: PASSTHROUGH
    hosts:
    - {{ .Values.istio.host | quote }}
{{- end }}
