{{- if .Values.keyVault.enabled }}
apiVersion: secrets-store.csi.x-k8s.io/v1
kind: SecretProviderClass
metadata:
  name: {{ .Release.Name }}-keyvault-secrets
  namespace: {{ .Release.Namespace }}
  labels:
    {{- include "universal-controller.labels" . | nindent 4 }}
    app.kubernetes.io/component: keyvault
spec:
  provider: azure
  parameters:
    usePodIdentity: "false"
    useVMManagedIdentity: "true"
    userAssignedIdentityID: {{ .Values.keyVault.managedIdentityClientId | quote }}
    tenantId: {{ .Values.keyVault.tenantId | quote }}                            
    keyvaultName: {{ .Values.keyVault.name | quote }}
    objects: |
      array:
      {{- range .Values.keyVault.secrets }}
        - |
          objectName: {{ .name }}
          objectType: secret
          objectVersion: ""
      {{- end }}
  secretObjects:
    - secretName: {{ .Release.Name }}-keyvault-passwords
      type: Opaque
      data:
      {{- range .Values.keyVault.secrets }}
        - objectName: {{ .name }}
          key: {{ .key }}
      {{- end }}
{{- end }}
